### ISSUE TITLE
Support OutputLocation for athena.query> operator

### ISSUE THREAD

**Issue by y-ken** [civitaspo/digdag-operator-athena#85]
Would you please support `OutputLocation` customization?
> The location in Amazon S3 where your query results are stored, such as s3://path/to/query/bucket/ . 
https://docs.aws.amazon.com/cli/latest/reference/athena/start-query-execution.html

From my investigation, JAVA SDK supports ResultConfiguration to set `setOutputLocation()`.
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/athena/model/ResultConfiguration.html

This base class does not have `outputLocation` customize feature.
https://github.com/civitaspo/digdag-operator-athena/blob/079bfd4ad7ccd3a466c0e69f6b6f355a6307bcf8/src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/athena/Athena.scala

I have tested on my local that aws CLI supports like this.
```
$ aws athena start-query-execution --query-string "SELECT 1" --result-configuration OutputLocation=s3://test_athena/athena_result --region us-east-1
```

**Comment by civitaspo** [comment]
[As I said in Twitter (in Japanese)](https://twitter.com/Civitaspo/status/1290085727426842624), this is not a feature I want to implement for use in ETL because `athena.ctas>` operator and `athena.apas>` operator are designed for that purpose. I'm not going to reject Pull Requests about this feature, so please make a Pull Request if you need it.
